---
# tasks file for networking-add-ssh-keys/

- block:  
      - name: Add ssh keys to nxos device via delegate_to host with password
        nxos_config:
            src: config.j2
            provider: "{{ provider }}"
        register: output
        delegate_to: "{{ netkeys_delegate_to }}"
        connection: local

      - debug: var=output

  when: netkeys_delegate_to is defined and netkeys_password is defined

- block:
      - name: Add ssh keys to nxos device via delegate_to host no password
        nxos_config:
            src: config.j2
            provider: "{{ provider }}"
        register: output
        delegate_to: "{{ netkeys_delegate_to }}"
        connection: local
 
      - debug: var=output

  when: netkeys_delegate_to is defined and netkeys_password is not defined

- block:
      - name: Add ssh keys to nxos device directly with password
        nxos_config:
            src: config.j2
            provider: "{{ provider }}"
        register: output
        connection: local

      - debug: var=output

  when: netkeys_delegate_to is not defined and netkeys_password is defined

- block:
      - name: Add ssh keys to nxos device directly no password
        nxos_config:
            src: config.j2
            provider: "{{ provider }}"
        register: output
        connection: local

      - debug: var=output

  when: netkeys_delegate_to is not defined and netkeys_password is not defined
